BASE=`pwd`
LIB=$(BASE)/lib
SETTINGS=$(BASE)/settings
APPS=$(BASE)/apps
PYTHONPATH=$(BASE):$(LIB):$(APPS):$(SETTINGS)
SETTINGS_LOCAL=settings.dev
SETTINGS_HEROKU=settings.deploy
MANAGE=$(BASE)/manage.py

init:
	pip install -r requirements/dev.txt
	DJANGO_SETTINGS_MODULE=$(SETTINGS_LOCAL) $(MANAGE) syncdb --noinput
	DJANGO_SETTINGS_MODULE=$(SETTINGS_LOCAL) $(MANAGE) loaddata db_data.json
manage:
	DJANGO_SETTINGS_MODULE=$(SETTINGS_LOCAL) $(MANAGE) $(COMMAND)

run:
	DJANGO_SETTINGS_MODULE=$(SETTINGS_LOCAL) $(MANAGE) runserver

test:
	DJANGO_SETTINGS_MODULE=$(SETTINGS_LOCAL) $(MANAGE) test $(APP)
runheroku:
	DJANGO_SETTINGS_MODULE=$(SETTINGS_HEROKU) $(MANAGE) syncdb --noinput
	DJANGO_SETTINGS_MODULE=$(SETTINGS_HEROKU) $(MANAGE) loaddata db_data.json
	DJANGO_SETTINGS_MODULE=$(SETTINGS_HEROKU) $(MANAGE) runserver 0.0.0.0:$(PORT)
